variable "cidr_block" {}
variable "public_subnet_cidr_block" {}
variable "dqdb_apps_cidr_block" {}
variable "ext_feed_apps_cidr_block" {}
variable "data_ingest_apps_cidr_block" {}
variable "data_pipe_apps_cidr_block" {}
variable "mdm_apps_cidr_block" {}
variable "int_dashboard_cidr_block" {}
variable "ext_dashboard_cidr_block" {}
variable "az" {}
variable "name_prefix" {}
